In [17]:
from utility import jaccard as jac_np
from utility import point_form as pf_np
from utility import intersect as int_np

from box_utils  import jaccard as jac_torch
from box_utils  import point_form as pf_torch
from box_utils  import intersect  as int_torch 

from CustomDataLoaderTesting import DataAugmentor
import numpy as np
import torch
from pathlib import Path
import collections
from SSD_generate_anchors import generate_ssd_priors

In [18]:
SSDBoxSizes = collections.namedtuple('SSDBoxSizes', ['min', 'max'])

Spec = collections.namedtuple('Spec', ['feature_map_size', 'shrinkage', 'box_sizes', 
                                       'aspect_ratios'])

# the SSD orignal specs
specs = [
    Spec(38, 8, SSDBoxSizes(30, 60), [2]),
    Spec(19, 16, SSDBoxSizes(60, 111), [2, 3]),
    Spec(10, 32, SSDBoxSizes(111, 162), [2, 3]),
    Spec(5, 64, SSDBoxSizes(162, 213), [2, 3]),
    Spec(3, 100, SSDBoxSizes(213, 264), [2]),
    Spec(1, 300, SSDBoxSizes(264, 315), [2])
]

priors = generate_ssd_priors(specs)

In [19]:
root   = Path.home()/'Documents'/'DATASETS'/'VOCdevkit'/'VOC2007'
voc_image_path      = root/'JPEGImages'
voc_annotation_path = root/'Annotations'
voc_trainval_path   = root/'ImageSets'/'Main'/'train.txt'



In [20]:
tester = DataAugmentor()
generator = tester.flow_from_directory(root        = root,
                                       data_file   = voc_trainval_path,
                                       target_size = 300,
                                       batch_size  = 1,
                                       shuffle = True)

In [21]:
_ , target = generator[0]

conf_data = target[0][:,0]
loc_data  = target[0][:,1:]

In [22]:

loc_data_np = pf_np(loc_data)                    # point form numpy 
priors_np   = pf_np(priors).astype(np.float32)   # point form numpy

print(loc_data)
print(loc_data_np)


[[0.305      0.568      0.624      0.542     ]
 [0.732      0.53066665 0.26133335 0.404     ]]
[[-0.007       0.29700002  0.617       0.839     ]
 [ 0.6013333   0.32866663  0.86266667  0.7326667 ]]


In [23]:

loc_data_th = torch.from_numpy(loc_data)

priors_th   = torch.from_numpy(priors_np).float()

loc_data_th_pf = pf_torch(loc_data_th) # point from in torch
# priors_th_pf   = pf_torch(priors_th)   # point form in torch

print(loc_data_th)
print(loc_data_th_pf)

tensor([[0.3050, 0.5680, 0.6240, 0.5420],
        [0.7320, 0.5307, 0.2613, 0.4040]])
tensor([[-0.0070,  0.2970,  0.6170,  0.8390],
        [ 0.6013,  0.3287,  0.8627,  0.7327]])


In [24]:
loc_data_th.size()

torch.Size([2, 4])

In [25]:
iou_np = jac_np(box_a = loc_data_np, box_b = priors_np)
iou_th = jac_torch(box_a = loc_data_th_pf, box_b= priors_th)

In [26]:
a = (iou_np == iou_th.numpy())

In [27]:
np.sum(a)

17464

In [86]:
def encode_np(matched = None, priors = None, variances = [0.1, 0.2]):
    '''
    Encode the variance from the priorbox layers inot the ground truth boxes 
    we have macthed  (based on jaccard overlap) with the prior boxes
    Args:
        matched:  (tensor) coords of ground truth for each prior in point_form 
                   shape = [num_priors, 4]
       priors  : (tensor) priors boxes in center-offset form 
                   shape = [num_priors, 4]
       variance: list(float) Variance of prior boxes

    Returns:
        encoded boxes: (tensor) shape = [num_priors, 4]
    '''
    g_cxcy = (matched[:,:2] + matched[:,:2])/2 - priors[:,:2]
    
    # encoded variance
    g_cxcy /= (variances[0] * priors[:,2:])
    
    # match width/height with priors width and height
    g_wh  = (matched[:,2:] - matched[:,:2]) / priors[:,2:]
    g_wh  = np.log(g_wh) / variances[1]
    
    return np.concatenate((g_cxcy, g_wh), axis = -1)

def encode_torch(matched, priors, variances):
    """Encode the variances from the priorbox layers into the ground truth boxes
    we have matched (based on jaccard overlap) with the prior boxes.
    Args:
        matched: (tensor) Coords of ground truth for each prior in point-form
            Shape: [num_priors, 4].
        priors: (tensor) Prior boxes in center-offset form
            Shape: [num_priors,4].
        variances: (list[float]) Variances of priorboxes
    Return:
        encoded boxes (tensor), Shape: [num_priors, 4]
    """

    # dist b/t match center and prior's center
    g_cxcy = (matched[:, :2] + matched[:, 2:])/2 - priors[:, :2]
    
    # encode variance
    g_cxcy /= (variances[0] * priors[:, 2:])
    
    # match wh / prior wh
    g_wh = (matched[:, 2:] - matched[:, :2]) / priors[:, 2:]
    g_wh = torch.log(g_wh) / variances[1]
    
    # return target for smooth_l1_loss
    return torch.cat([g_cxcy, g_wh], 1)  # [num_priors,4]

In [88]:
def numpy_argmax(a, axis = 0):
    
    if not axis == 0:
        raise ValueError('to be used only for axis 0')
    
    row, col = a.shape[:2]
    output = []
    for i in range(col):
        x = a[:,i]
        index = np.where(x == x.max(axis = 0))[0][-1] # the last entry in the array
        output.append(index)
        
    return np.array(output)

def index_fill(array, index, axis, value):
    dim = array.shape
    
    if axis == 1:
        for i in range(dim[0]):
            np.put(array[i,:], index, value)
            
    elif axis == 0:
        for i in range(dim[1]):
            np.put(array[:,i], index, value)
            
    return array

def match_np(truths      = None, 
          labels     = None, 
          priors     = None, 
          variance   = None, 
          threshold  = 0.5,
        ):

    
    iou = jac_np(truths, priors)
    
    best_prior_overlap = np.amax(iou, axis=-1).astype(np.float32)
    best_prior_idx     = np.argmax(iou, axis =-1)
    
# #    print(best_prior_overlap.shape)
# #    print(best_prior_idx.shape)

    best_truth_overlap = np.amax(iou, axis=0).astype(np.float32)
    best_truth_idx     = numpy_argmax(iou)
    
#     best_truth_overlap = index_fill(best_truth_overlap, best_prior_idx, axis=0, value=2)   
# #    print(best_truth_overlap.shape)
# #    print(best_truth_idx.shape)

    for j in range(best_prior_idx.shape[0]):
        best_truth_idx[best_prior_idx[j]] = j
    
    matches = truths[best_truth_idx]
    
#     conf    = labels[best_truth_idx]
#     conf[best_truth_overlap < threshold] = 0
    
    loc     = encode_np(matched=matches, priors=priors, variances=variance)
    
    return loc 


def match_torch(threshold = 0.5, 
                truths = None, 
                priors = None, 
                variances = [0.1, 0.2], 
                labels = None):
    
    overlaps = jac_torch(truths, priors)
    
    # (Bipartite Matching)
    # [1,num_objects] best prior for each ground truth
    best_prior_overlap, best_prior_idx = overlaps.max(1, keepdim=True)
#     # [1,num_priors] best ground truth for each prior
    best_truth_overlap, best_truth_idx = overlaps.max(0, keepdim=True)
    
    best_truth_idx.squeeze_(0)
    best_truth_overlap.squeeze_(0)
    best_prior_idx.squeeze_(1)
    best_prior_overlap.squeeze_(1)
    
    best_truth_overlap.index_fill_(0, best_prior_idx, 2)  # ensure best prior
    
    # TODO refactor: index  best_prior_idx with long tensor
    # ensure every gt matches with its prior of max overlap
    for j in range(best_prior_idx.size(0)):
        best_truth_idx[best_prior_idx[j]] = j
        
    matches = truths[best_truth_idx]          # Shape: [num_priors,4]
    
#     conf = labels[best_truth_idx] + 1         # Shape: [num_priors]
#     conf[best_truth_overlap < threshold] = 0  # label as background
    loc = encode_torch(matches, priors, variances)

    return  loc 

In [89]:
bestPO_np  = match_np(truths=loc_data_np, priors=priors_np, threshold=0.5, variance=[0.1,0.2], labels=None)
bestPO_th  = match_torch(truths=loc_data_th_pf, priors=priors_th, threshold=0.5)

In [90]:
bestPO_np.shape

(8732, 4)

In [91]:
bestPO_th.size()

torch.Size([8732, 4])

In [92]:
c = (bestPO_np == bestPO_th.numpy())
np.sum(c)

17464

In [93]:
c

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True],
       ...,
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True]])