In [1]:
import torch
from keras import backend as K
import tensorflow as tf
import numpy as np

Using TensorFlow backend.


In [5]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

In [6]:
t

tensor([[1, 2],
        [3, 4]])

In [17]:
tt = np.array([[1,2],[3,4]])
index = np.array([[0,0],[1,0]])

out = K.tf.gather_nd(tt, index, batch_dims=0)

In [18]:
K.eval(out)

array([1, 3])

In [29]:
ttt = tt.reshape(-1)
out2 = K.tf.gather(ttt, index)
K.eval(out2)

array([[1, 1],
       [2, 1]])

In [34]:
test = 
for i in range(index.shape[0]):
    for j in range(index.shape[1]):
        a =  K.gather(tt[i,:], index[i,j])
        test.append(K.eval(a))

In [36]:
test = np.array()
test.reshape(index.shape)

AttributeError: 'list' object has no attribute 'reshape'

In [27]:



def gather(self, dim, index):
    """
    Gathers values along an axis specified by ``dim``.

    For a 3-D tensor the output is specified by:
        out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
        out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
        out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2

    Parameters
    ----------
    dim:
        The axis along which to index
    index:
        A tensor of indices of elements to gather

    Returns
    -------
    Output Tensor
    """
    idx_xsection_shape = index.shape[:dim] + \
        index.shape[dim + 1:]
    self_xsection_shape = self.shape[:dim] + self.shape[dim + 1:]
    if idx_xsection_shape != self_xsection_shape:
        raise ValueError("Except for dimension " + str(dim) +
                         ", all dimensions of index and self should be the same size")
    if index.dtype != np.dtype('int_'):
        raise TypeError("The values of index must be integers")
    data_swaped = np.swapaxes(self, 0, dim)
    index_swaped = np.swapaxes(index, 0, dim)
    gathered = np.choose(index_swaped, data_swaped)
    return np.swapaxes(gathered, 0, dim)

In [ ]:
def gather_keras(self, dim, index):
    idx_xsection_shape = K.shape(index)[:dim] + K.shape(index)[dim + 1:]
    
    self_xsection_shape = K.shape(self)[:dim] + K.shape(self)[dim + 1:]
    
    data_swaped = K.tf.transpose(self, [0, dim])
    index_swaped = K.tf.transpose(index, [0, dim])
    
    